2023-09-16 18:31:13.057 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-16 18:31:13.060 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-16 21:44:13.203 WARNING (Bot:6519705554:updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x5d63b910>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot6519705554:AAEPBCMvaym_OTNjOawGmdVjSiOscMr6GyA/getUpdates
2023-09-16 21:44:18.272 WARNING (Bot:6519705554:updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x5d62d070>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot6519705554:AAEPBCMvaym_OTNjOawGmdVjSiOscMr6GyA/getUpdates
2023-09-17 22:02:45.005 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1525360872] Error handling message: Integration '' not found (unknown_error) Clement from 192.168.1.4 (Mozilla/5.0 (iPhone; CPU iPhone OS 16_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.4 (io.robbie.HomeAssistant; build:2023.460; iOS 16.6.1) Mobile/HomeAssistant, like Safari)
2023-09-18 09:50:11.040 WARNING (Bot:6519705554:updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x5f4c4a90>: Failed to establish a new connection: [Errno -3] Try again')': /bot6519705554:AAEPBCMvaym_OTNjOawGmdVjSiOscMr6GyA/getUpdates
2023-09-18 09:50:16.049 WARNING (Bot:6519705554:updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x5a4de790>: Failed to establish a new connection: [Errno -3] Try again')': /bot6519705554:AAEPBCMvaym_OTNjOawGmdVjSiOscMr6GyA/getUpdates
2023-09-18 09:50:21.060 WARNING (Bot:6519705554:updater) [telegram.vendor.ptb_urllib3.urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x5bff76b0>: Failed to establish a new connection: [Errno -3] Try again')': /bot6519705554:AAEPBCMvaym_OTNjOawGmdVjSiOscMr6GyA/getUpdates
